language: python
os: linux

python:
 - "3.7"

install:
 - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 - source $HOME/.cargo/env

script:
 - cargo build --manifest-path amp/Cargo.toml
 - cargo build --manifest-path midigate/Cargo.toml
 - cargo build --manifest-path fifths/Cargo.toml
 - python3 make_book.py
 - cat export/index.md

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN
  on:
    branch: master
  target_branch: gh-pages
  local_dir: export