language: python
os: linux

python:
 - "3.7"

script:
 - make export/book.md

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN
  on:
    branch: master
  target_branch: gh-pages
  local_dir: export