language: rust
os: linux

script:
 - cargo build --manifest-path amp
 - cargo build --manifest-path midigate
 - cargo build --manifest-path fifths
 - python3 make_book.py

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN
  on:
    branch: master
  target_branch: gh-pages
  local_dir: export