[package]
name = "eg-fifths-rs"
version = "0.1.0"
authors = ["Janonard <janonard@protonmail.com>"]
license = "ISC"
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
lv2rs = "0.3.0"
ux = "*"

[patch.crates-io]
lv2rs = { git = "https://github.com/Janonard/lv2rs.git" }
