[package]
name = "eg-amp-rs"
version = "0.2.0"
authors = ["Janonard <janonard@protonmail.com>"]
license = "ISC"
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
lv2rs = { git = "https://github.com/Janonard/lv2rs.git" }