[package]
name = "eg-amp-rs"
version = "0.2.0"
authors = ["Janonard <janonard@protonmail.com>"]
license = "ISC"
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
lv2-core = { git = "https://github.com/RustAudio/rust-lv2.git" }